### ISSUE TITLE
MALAPI.keys?

### ISSUE THREAD

**Issue by Idgardio** [mik2003/MAL-playlist#2]
so after moving main outside of the project folder and creating a cache folder myself, the project still has issues running as is, looking for files not present:
project\\.secret\\mal_api.json

**Comment by mik2003** [comment]
I am sorry, I forgot to mention in the README that you need to make your own MAL API keys and put them in that location (project/.secret/mal_api.json or just change the script to the location you want), you can make the keys [https://myanimelist.net/apiconfig](here). Hope this helps! Keep in mind that this is just my personal project so there are bugs for sure, just let me know if I can help you further.

**Comment by mik2003** [comment]
You can look at the updated README, I added instructions on what you should do for the MAL API key.
